services:
  mc:
    image: itzg/minecraft-server
    ports:
    # expose the Minecraft server port outside of container
    - "25565:25565"
    - "25575:25575"
    - "19132:19132/udp"
    stdin_open: true
    tty: true
    environment:
      EULA: true
      # Set server type (vs the default of vanilla)
      TYPE: PAPER
      # gets the latest if not set explicitly
      #VERSION: "1.21.3"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      MOTD: "Raspberry Pi - Roccos  minecraft server in action"
      OPS: "rocpop62"
      MODE: survival
      UID: 1000
      GID: 1000
      TZ: "Australia/Melbourne" # Timezone
      MEMORY: "2G"
    volumes:
    # use a named, managed volume for data volume
    - ./minecraft-data:/data
    restart: unless-stopped
volumes:
  # declared the named volume, but use default/local storage engine
  minecraft-data: {}

